---
title: "Webscraping to Find Key DS Skills"
author: "Dream Team"
date: '2017-10-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Project 3

The goal of project 3 is to find key skills for data scientists and put these into a relational database as well as perform some baisic data analysis.

### Loading Libraries.

```{r message= FALSE, warning=FALSE}
library(RCurl)
library(xml2)
library(rvest)
library(knitr)
```

Function to find multiple URLs for all cities:

```{r}
# Functions
itter <- c("", "&start=10", "&start=20", "&start=30")
IndeedCities <- function(jobTitle, city, state){
  url <- c() #To make a list with multiple returns.
  for(i in itter){ # create urls
  i <- paste0("https://www.indeed.com/jobs?q=",
                gsub(" ", replacement = "+", jobTitle),
                "&l=",
                gsub(" ", replacement = "+", city),
                "%2C+", 
                state, 
                i,
                sep = "")
  url <- c(url, i) #Update list of urls
  }
  return(url)
}
```

The cities we will search over. 
```{r}
nyc <-  IndeedCities("Data Scientist", "New York", "NY")
bost <- IndeedCities("Data Scientist", "Boston", "MA")
sanFran <- IndeedCities("Data Scientist", "San Francisco", "CA")
hust <- IndeedCities("Data Scientist", "Houston", "TX")
sea <- IndeedCities("Data Scientist", "Seattle", "WA")
```


Function to create the city data.frames

```{r}
df1 <- data.frame(CompanyName = as.character(),
                  TitleName = as.character(),
                  City = as.character(),
                  ExperienceList = as.character())
url <- "https://www.indeed.com/jobs?q=data+science&l=New+York" #Test URL
IndeedData <- function(x){
  for(i in c(1:4)){
    ineeedPage <- read_html(x[i]) # reading to make a list.

   #Creating columns of the dataframe:

   ExperienceList <- ineeedPage %>%
      html_nodes(".experienceList") %>%
      html_text()

    TitleName <- ineeedPage %>%
     html_nodes(".jobtitle") %>%
     html_text()

    CompanyName <- ineeedPage %>%
      html_nodes(".company") %>%
      html_text()

    City <- ineeedPage %>%
      html_nodes(".location") %>%
      html_text()
    # Make a list of all the text in the webpage. 
    test <- ineeedPage %>%
      html_nodes(".result") %>%
      html_text()
# Make sure that experience is actually included.
    for(j in 1:length(test)) {
      if (grepl("Desired Experience:",x = test[j])) {
        #print(j)
      } else {
        ExperienceList <-  append(ExperienceList, NA, after=(i))
  }
}
    df <- data.frame(CompanyName,TitleName, City, ExperienceList)
    df1 <- rbind(df1,df)
  }
 return(df1)
}

```

Create the city dfs

```{r}
nycDF <- IndeedData(nyc) 
bostDF <- IndeedData(bost)
sanFranDF <- IndeedData(sanFran)
hustDF <- IndeedData(hust)
seaDF <- IndeedData(sea)
```

Create one single df.
```{r}
df <- rbind(nycDF, bostDF, sanFranDF, hustDF, seaDF)
df %>% kable()
```


```{r}
# lapply(df$ExperienceList, function(x) unique(trimws(unlist(strsplit(x, ",")))))
# 
# lapply(df$ExperienceList, function(x) sprintf("[%s]", paste(x, collapse = ",")))
```

```{r}

skillCount <- paste(df$ExperienceList, collapse = ",") 
skillCount <-  strsplit(skillCount, ",")[[1]]
skillCount <- gsub(" ", "", skillCount)
skillTable <-  table(skillCount) %>% as.data.frame()
```

```{r}

library(ggplot2)

  ggplot(skillTable, aes(x = reorder(skillCount, Freq), y = Freq)) + 
  geom_bar(stat = "identity") +
  ggtitle("Percentage of Non- Missing Values") +
  coord_flip() 
```

